// Generated by build.py — do not edit by hand.
// Precaches the whole playground so the games work with no connection.
const CACHE = "playground-6f6f503ae5dc";
const PRECACHE = [
 "./playground/jeux-enfants.html",
 "./playground/assets/279600cd-a450-41d4-bb16-a49caaf05e28.jpeg",
 "./playground/assets/animaux/bear.jpg",
 "./playground/assets/animaux/cat.jpg",
 "./playground/assets/animaux/cattle.jpg",
 "./playground/assets/animaux/deer.jpg",
 "./playground/assets/animaux/dog.jpg",
 "./playground/assets/animaux/dolphin.jpg",
 "./playground/assets/animaux/duck.jpg",
 "./playground/assets/animaux/eagle.jpg",
 "./playground/assets/animaux/elephant.jpg",
 "./playground/assets/animaux/frog.jpg",
 "./playground/assets/animaux/giraffe.jpg",
 "./playground/assets/animaux/gorilla.jpg",
 "./playground/assets/animaux/horse.jpg",
 "./playground/assets/animaux/lion.jpg",
 "./playground/assets/animaux/owl.jpg",
 "./playground/assets/animaux/pig.jpg",
 "./playground/assets/animaux/rabbit.jpg",
 "./playground/assets/animaux/red_fox.jpg",
 "./playground/assets/animaux/shark.jpg",
 "./playground/assets/animaux/sheep.jpg",
 "./playground/assets/animaux/snake.jpg",
 "./playground/assets/animaux/tiger.jpg",
 "./playground/assets/animaux/turtle.jpg",
 "./playground/assets/animaux/whale.jpg",
 "./playground/assets/animaux/wolf.jpg",
 "./playground/assets/animaux/zebra.jpg",
 "./playground/assets/chess.min.js",
 "./playground/assets/countries-110m.json",
 "./playground/assets/d3.min.js",
 "./playground/assets/dinos/allosaurus.jpg",
 "./playground/assets/dinos/ankylosaurus.jpg",
 "./playground/assets/dinos/brachiosaurus.jpg",
 "./playground/assets/dinos/deinonychus.jpg",
 "./playground/assets/dinos/hypsilophodon.jpg",
 "./playground/assets/dinos/iguanodon.jpg",
 "./playground/assets/dinos/pachycephalosaurus.jpg",
 "./playground/assets/dinos/parasaurolophus.jpg",
 "./playground/assets/dinos/plesiosaurus.jpg",
 "./playground/assets/dinos/pteranodon.jpg",
 "./playground/assets/dinos/rhamphorhynchus.jpg",
 "./playground/assets/dinos/spinosaurus.jpg",
 "./playground/assets/dinos/stegosaurus.jpg",
 "./playground/assets/dinos/triceratops.jpg",
 "./playground/assets/dinos/tyrannosaurus.jpg",
 "./playground/assets/dinos/velociraptor.jpg",
 "./playground/assets/fausses_definitions.js",
 "./playground/assets/fausses_definitions.json",
 "./playground/assets/puzzles.js",
 "./playground/assets/topojson-client.min.js",
 "./playground/assets/vraies_definitions.js",
 "./playground/assets/vraies_definitions.json",
 "./playground/assets/word_embeddings.json",
 "./playground/blocs-des-dizaines.html",
 "./playground/carte-au-tresor.html",
 "./playground/chateau-des-additions-et-des-mots.html",
 "./playground/chess-star-collector.html",
 "./playground/complete-la-phrase.html",
 "./playground/construis-la-route.html",
 "./playground/convoyeur-lettres.html",
 "./playground/course-des-additions.html",
 "./playground/course-des-couleurs.html",
 "./playground/dictee-de-lettres.html",
 "./playground/feux-de-circulation.html",
 "./playground/fusee-des-mots-nombres.html",
 "./playground/garage-des-vehicules.html",
 "./playground/grand-rush-hour.html",
 "./playground/habitats-du-monde.html",
 "./playground/jeu-additions.html",
 "./playground/jeu-capitales-2.html",
 "./playground/jeu-capitales.html",
 "./playground/jeu-de-simon.html",
 "./playground/jeu-des-animaux.html",
 "./playground/jeu-des-des.html",
 "./playground/jeu-dictionnaire.html",
 "./playground/jeu-dinosaures.html",
 "./playground/jeu-drapeaux-2.html",
 "./playground/jeu-drapeaux.html",
 "./playground/jeu-geographie-2.html",
 "./playground/jeu-geographie.html",
 "./playground/jeu-images.html",
 "./playground/jeu-mots.html",
 "./playground/jeu-phrases.html",
 "./playground/jeu-planetes.html",
 "./playground/jeu-sons.html",
 "./playground/jeu-traduction.html",
 "./playground/jeux-enfants.html",
 "./playground/l-ascenseur-de-l-espace.html",
 "./playground/la-cible-de-ballons.html",
 "./playground/le-corps-humain.html",
 "./playground/le-depanneur.html",
 "./playground/le-miroir-magique.html",
 "./playground/le-petit-professeur.html",
 "./playground/le-pont-des-additions.html",
 "./playground/le-verger-des-multiplications.html",
 "./playground/lecture-de-l-heure.html",
 "./playground/les-nombres-magiques.html",
 "./playground/livreur-en-ville.html",
 "./playground/monstres-nombres.html",
 "./playground/mots-fr-en.html",
 "./playground/ordre-des-planetes.html",
 "./playground/peche-aux-nombres-et-aux-mots.html",
 "./playground/petit-rush-hour.html",
 "./playground/serpents-et-echelles.html",
 "./playground/sudoku-des-animaux.html",
 "./playground/suites-logiques.html",
 "./playground/tir-au-but-additions.html",
 "./playground/trouve-le-mat.html"
];

self.addEventListener("install", event => {
  event.waitUntil(
    caches.open(CACHE)
      // addAll is atomic; one bad entry would discard everything, so add
      // individually and let a single failure be survivable.
      .then(c => Promise.all(PRECACHE.map(u => c.add(u).catch(() => null))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", event => {
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// Cache-first: offline is the point, and every cached file is versioned above.
self.addEventListener("fetch", event => {
  const req = event.request;
  if (req.method !== "GET" || new URL(req.url).origin !== self.location.origin) return;
  event.respondWith(
    caches.match(req, { ignoreSearch: true }).then(hit => hit || fetch(req).catch(() => hit))
  );
});
