// Generated by build.py — do not edit by hand.
// Precaches the whole playground so the games work with no connection.
const CACHE = "playground-e46a9894b776";
const PRECACHE = [
 "./playground/jeux-enfants.html",
 "./espanol/assets/audio/abuela.m4a",
 "./espanol/assets/audio/abuelo.m4a",
 "./espanol/assets/audio/adios.m4a",
 "./espanol/assets/audio/agua.m4a",
 "./espanol/assets/audio/amarillo.m4a",
 "./espanol/assets/audio/azul.m4a",
 "./espanol/assets/audio/blanco.m4a",
 "./espanol/assets/audio/buenas-noches.m4a",
 "./espanol/assets/audio/buenos-dias.m4a",
 "./espanol/assets/audio/caballo.m4a",
 "./espanol/assets/audio/cinco.m4a",
 "./espanol/assets/audio/cuatro.m4a",
 "./espanol/assets/audio/dos.m4a",
 "./espanol/assets/audio/fr-adios.m4a",
 "./espanol/assets/audio/fr-buenas-noches.m4a",
 "./espanol/assets/audio/fr-buenos-dias.m4a",
 "./espanol/assets/audio/fr-gracias.m4a",
 "./espanol/assets/audio/fr-hola.m4a",
 "./espanol/assets/audio/fr-si.m4a",
 "./espanol/assets/audio/gato.m4a",
 "./espanol/assets/audio/gracias.m4a",
 "./espanol/assets/audio/hermana.m4a",
 "./espanol/assets/audio/hermano.m4a",
 "./espanol/assets/audio/hola.m4a",
 "./espanol/assets/audio/huevo.m4a",
 "./espanol/assets/audio/leche.m4a",
 "./espanol/assets/audio/mama.m4a",
 "./espanol/assets/audio/manzana.m4a",
 "./espanol/assets/audio/negro.m4a",
 "./espanol/assets/audio/pajaro.m4a",
 "./espanol/assets/audio/pan.m4a",
 "./espanol/assets/audio/papa.m4a",
 "./espanol/assets/audio/perro.m4a",
 "./espanol/assets/audio/pez.m4a",
 "./espanol/assets/audio/queso.m4a",
 "./espanol/assets/audio/rojo.m4a",
 "./espanol/assets/audio/seis.m4a",
 "./espanol/assets/audio/si.m4a",
 "./espanol/assets/audio/tres.m4a",
 "./espanol/assets/audio/uno.m4a",
 "./espanol/assets/audio/vaca.m4a",
 "./espanol/assets/audio/verde.m4a",
 "./espanol/assets/media.js",
 "./espanol/curriculum.js",
 "./espanol/index.html",
 "./playground/assets/279600cd-a450-41d4-bb16-a49caaf05e28.jpeg",
 "./playground/assets/animaux/bear.jpg",
 "./playground/assets/animaux/cat.jpg",
 "./playground/assets/animaux/cattle.jpg",
 "./playground/assets/animaux/deer.jpg",
 "./playground/assets/animaux/dog.jpg",
 "./playground/assets/animaux/dolphin.jpg",
 "./playground/assets/animaux/duck.jpg",
 "./playground/assets/animaux/eagle.jpg",
 "./playground/assets/animaux/elephant.jpg",
 "./playground/assets/animaux/frog.jpg",
 "./playground/assets/animaux/giraffe.jpg",
 "./playground/assets/animaux/gorilla.jpg",
 "./playground/assets/animaux/horse.jpg",
 "./playground/assets/animaux/lion.jpg",
 "./playground/assets/animaux/owl.jpg",
 "./playground/assets/animaux/pig.jpg",
 "./playground/assets/animaux/rabbit.jpg",
 "./playground/assets/animaux/red_fox.jpg",
 "./playground/assets/animaux/shark.jpg",
 "./playground/assets/animaux/sheep.jpg",
 "./playground/assets/animaux/snake.jpg",
 "./playground/assets/animaux/tiger.jpg",
 "./playground/assets/animaux/turtle.jpg",
 "./playground/assets/animaux/whale.jpg",
 "./playground/assets/animaux/wolf.jpg",
 "./playground/assets/animaux/zebra.jpg",
 "./playground/assets/chess.min.js",
 "./playground/assets/countries-110m.json",
 "./playground/assets/d3.min.js",
 "./playground/assets/dinos/allosaurus.jpg",
 "./playground/assets/dinos/ankylosaurus.jpg",
 "./playground/assets/dinos/brachiosaurus.jpg",
 "./playground/assets/dinos/deinonychus.jpg",
 "./playground/assets/dinos/hypsilophodon.jpg",
 "./playground/assets/dinos/iguanodon.jpg",
 "./playground/assets/dinos/pachycephalosaurus.jpg",
 "./playground/assets/dinos/parasaurolophus.jpg",
 "./playground/assets/dinos/plesiosaurus.jpg",
 "./playground/assets/dinos/pteranodon.jpg",
 "./playground/assets/dinos/rhamphorhynchus.jpg",
 "./playground/assets/dinos/spinosaurus.jpg",
 "./playground/assets/dinos/stegosaurus.jpg",
 "./playground/assets/dinos/triceratops.jpg",
 "./playground/assets/dinos/tyrannosaurus.jpg",
 "./playground/assets/dinos/velociraptor.jpg",
 "./playground/assets/fausses_definitions.js",
 "./playground/assets/fausses_definitions.json",
 "./playground/assets/puzzles.js",
 "./playground/assets/topojson-client.min.js",
 "./playground/assets/vraies_definitions.js",
 "./playground/assets/vraies_definitions.json",
 "./playground/assets/word_embeddings.json",
 "./playground/blocs-des-dizaines.html",
 "./playground/carte-au-tresor.html",
 "./playground/chateau-des-additions-et-des-mots.html",
 "./playground/chess-star-collector.html",
 "./playground/complete-la-phrase.html",
 "./playground/construis-la-route.html",
 "./playground/convoyeur-lettres.html",
 "./playground/course-des-additions.html",
 "./playground/course-des-couleurs.html",
 "./playground/dictee-de-lettres.html",
 "./playground/feux-de-circulation.html",
 "./playground/fusee-des-mots-nombres.html",
 "./playground/garage-des-vehicules.html",
 "./playground/grand-rush-hour.html",
 "./playground/habitats-du-monde.html",
 "./playground/jeu-additions.html",
 "./playground/jeu-capitales-2.html",
 "./playground/jeu-capitales.html",
 "./playground/jeu-de-simon.html",
 "./playground/jeu-des-animaux.html",
 "./playground/jeu-des-des.html",
 "./playground/jeu-dictionnaire.html",
 "./playground/jeu-dinosaures.html",
 "./playground/jeu-drapeaux-2.html",
 "./playground/jeu-drapeaux.html",
 "./playground/jeu-geographie-2.html",
 "./playground/jeu-geographie.html",
 "./playground/jeu-images.html",
 "./playground/jeu-mots.html",
 "./playground/jeu-phrases.html",
 "./playground/jeu-planetes.html",
 "./playground/jeu-sons.html",
 "./playground/jeu-traduction.html",
 "./playground/l-ascenseur-de-l-espace.html",
 "./playground/la-cible-de-ballons.html",
 "./playground/le-corps-humain.html",
 "./playground/le-depanneur.html",
 "./playground/le-miroir-magique.html",
 "./playground/le-partage.html",
 "./playground/le-petit-professeur.html",
 "./playground/le-pont-des-additions.html",
 "./playground/le-verger-des-multiplications.html",
 "./playground/lecture-de-l-heure.html",
 "./playground/les-nombres-magiques.html",
 "./playground/les-oiseaux-sur-le-fil.html",
 "./playground/livreur-en-ville.html",
 "./playground/monstres-nombres.html",
 "./playground/mots-fr-en.html",
 "./playground/ordre-des-planetes.html",
 "./playground/peche-aux-nombres-et-aux-mots.html",
 "./playground/petit-rush-hour.html",
 "./playground/range-les-blocs.html",
 "./playground/serpents-et-echelles.html",
 "./playground/sudoku-des-animaux.html",
 "./playground/suites-logiques.html",
 "./playground/tape-les-syllabes.html",
 "./playground/tir-au-but-additions.html",
 "./playground/trouve-le-mat.html"
];
const CONCURRENCY = 6;
const ATTEMPTS = 4;

async function tellClients(msg) {
  const clients = await self.clients.matchAll({ includeUncontrolled: true });
  for (const c of clients) c.postMessage(msg);
}

async function precacheAll() {
  const cache = await caches.open(CACHE);
  const have = new Set((await cache.keys()).map(r => new URL(r.url).pathname));
  let queue = PRECACHE.filter(u => !have.has(new URL(u, self.location).pathname));

  const total = PRECACHE.length;
  let done = total - queue.length;

  for (let attempt = 0; attempt < ATTEMPTS && queue.length; attempt++) {
    const pending = queue.slice();
    const failed = [];

    await Promise.all(Array.from({ length: CONCURRENCY }, async () => {
      while (pending.length) {
        const url = pending.shift();
        try {
          // Bypass the HTTP cache: filenames are stable across deploys, so a
          // stale cached copy would otherwise be baked in for a whole version.
          const res = await fetch(url, { cache: "reload" });
          if (!res.ok) throw new Error(res.status);
          await cache.put(url, res);
          done++;
          if (done % 10 === 0 || done === total) tellClients({ type: "precache", done, total });
        } catch (e) {
          failed.push(url);
        }
      }
    }));

    queue = failed;
    if (queue.length) await new Promise(r => setTimeout(r, 600 * (attempt + 1)));
  }

  await tellClients({ type: "precache", done, total, failed: queue.length });
  return queue.length;
}

self.addEventListener("install", event => {
  event.waitUntil(precacheAll().then(() => self.skipWaiting()));
});

self.addEventListener("activate", event => {
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// Lets a page ask how complete the cache is. Counts how many PRECACHE entries
// are actually present rather than the raw key count, which can also include
// pages stored at runtime.
self.addEventListener("message", event => {
  if (!event.data || event.data.type !== "status") return;
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    const have = new Set((await cache.keys()).map(r => new URL(r.url).pathname));
    const done = PRECACHE.filter(u => have.has(new URL(u, self.location).pathname)).length;
    await tellClients({ type: "precache", done, total: PRECACHE.length });
  })());
});

// The host rewrites links to drop the .html extension ("pretty URLs"), so a tap
// requests /playground/jeu-mots while the cache holds /playground/jeu-mots.html.
// Those are different cache keys, so look up every spelling of the same page.
async function matchPage(req) {
  const cache = await caches.open(CACHE);
  const direct = await cache.match(req, { ignoreSearch: true });
  if (direct) return direct;

  const url = new URL(req.url);
  const alts = [];
  if (url.pathname.endsWith("/")) {
    alts.push(url.pathname + "index.html");
  } else if (url.pathname.endsWith(".html")) {
    alts.push(url.pathname.slice(0, -5));
  } else {
    alts.push(url.pathname + ".html", url.pathname + "/index.html");
  }

  for (const p of alts) {
    const hit = await cache.match(url.origin + p, { ignoreSearch: true });
    if (hit) return hit;
  }
  return null;
}

self.addEventListener("fetch", event => {
  const req = event.request;
  if (req.method !== "GET" || new URL(req.url).origin !== self.location.origin) return;

  // Pages: network first, so a push shows up on the next load rather than
  // needing repeated reloads. Falls back to cache with no connection.
  if (req.mode === "navigate" || (req.headers.get("accept") || "").includes("text/html")) {
    event.respondWith(
      fetch(req)
        .then(res => {
          const copy = res.clone();
          caches.open(CACHE).then(c => c.put(req, copy)).catch(() => {});
          return res;
        })
        .catch(async () => (await matchPage(req))
          || (await caches.match("./playground/jeux-enfants.html")))
    );
    return;
  }

  // Assets: cache first, but store anything that was missed. This self-heals a
  // partial precache -- opening a game once while online makes it permanent.
  event.respondWith(
    caches.match(req, { ignoreSearch: true }).then(hit => {
      if (hit) return hit;
      return fetch(req).then(res => {
        if (res.ok) {
          const copy = res.clone();
          caches.open(CACHE).then(c => c.put(req, copy)).catch(() => {});
        }
        return res;
      }).catch(() => hit);
    })
  );
});
