---
title: "[Justin Savoie](https://www.justinsavoie.com/)"
format:
  html:
    embed-resources: true
editor: visual
---

### Notes

7 - [L'analyse quantitative en sciences sociales](Analyse-Quanti-Sciences-Sociales.html) (2023-10) Quelques réflexions sur l'analyse quantitative 

6 - [Notes from Lumley's Complex Surveys book](Lumley-Complex-Surveys.html) (2023-10) Notes and R code for illustrative purposes. Work in progress.

5 - [What is data analysis?](data-analysis.html) (2023-09) What various key authors say data analysis is.

4 - [Am I a Bayesian or a Frequentist?](being-bayesian-frequentist.html) (2023-09) A short reflection on the use of simple models in social science.

3 - [Scaling in regression](scaling-in-regression.html) (2023-05) Technical notes and R code about scaling before regression.

2 - [Logistic regression](logistic-regression.html) (2023-05) Technical notes and R code for derivation of logistic regression and associated statistics.

1 - [Multiple linear regression](multiple-linear-regression.html) (2023-05) Technical notes and R code for derivation of linear regression and associated statistics.
