---
title: "Multiple linear regression"
format: html
editor: visual
---

## Multiple linear regression

The [basic linear regression model](https://en.wikipedia.org/wiki/Linear_regression) takes the form $$y_i=\beta_0+\beta_1x_i+...+\beta_kx_{ik}+\varepsilon = x_i^T\beta+\varepsilon_i, i = 1,...,n$$

In matrix form $$y=X\beta+\varepsilon_i$$

$\hat{\beta}$, the vector of coefficients, can be obtained using matrix operations $$(X^TX)^{-1}X^Ty$$

In R

```{r}
d <- read.csv("https://stats.idre.ucla.edu/wp-content/uploads/2019/02/elemapi2v2.csv")
summary(fit <- lm(api00 ~  enroll + meals + full, data = d))
X <- as.matrix(cbind(1,d[,c("enroll","meals","full")]))
y <- d$api00
betas <- solve(t(X) %*% X) %*% t(X) %*% y
```

The variance of $\hat{\beta}$ is $Var(\hat{\beta})=\hat{\sigma^2}(X^TX)^{-1}$

```{r}
residuals <- y - (X %*% betas)
k <- ncol(X)-1
degrees_of_freedom <- nrow(X) - k - 1
residual_variance <- sum(residuals^2) / degrees_of_freedom 
betas_cov <- residual_variance * solve(t(X) %*% X)
betas_se <- sqrt(diag(betas_cov))
cbind(betas,betas_se)
```